folio-org/folio-module-sidecar

pom.xml

Fixes build issues with sidecar
While it's helpful for reviewers to help …

Fix sidecar build

---

src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilter.java
src/main/java/org/folio/sidecar/service/ServiceTokenProvider.java
src/test/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilterTest.java

Sidecar should return 403 Forbidden on authorization failure when a token is valid for the tenant and is not expired
JIRA: https://issues.folio.org/browse/MODSIDECAR-18
- Adjust authorization errors
- Update tests …

[MODSIDECAR-18] Fix authorization errors handling

---

src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakImpersonationFilter.java
src/main/java/org/folio/sidecar/service/ErrorHandler.java
src/test/java/org/folio/sidecar/it/SidecarIT.java
src/test/java/org/folio/sidecar/service/ErrorHandlerTest.java
src/test/java/org/folio/sidecar/service/routing/IngressRequestHandlerTest.java
src/test/resources/mappings/am/mod-foo-0.2.1-boostrap.json
src/test/resources/mappings/keycloak/evaluate-permissions-forbidden.json
src/test/resources/mappings/keycloak/evaluate-permissions-kc-error.json
src/test/resources/mappings/keycloak/evaluate-permissions-unauthorized.json
src/test/resources/mappings/keycloak/evaluate-permissions.json
src/test/resources/mappings/keycloak/obtain-admin-client-token.json
src/test/resources/mappings/keycloak/obtain-m2m-client-token.json
src/test/resources/mappings/keycloak/obtain-system-user-token.json

Improve auth error handling, add integration tests
JIRA: https://issues.folio.org/browse/MODSIDECAR-18
- Refactoring wiremock stubs for kc interactions
- Add integration tests to handle exceptions in KeycloakAuthorizationFilter
- Unify usage of ForbiddenException 
Ideally, all the PRs involved in breaking changes would be merged on the same …

[MODSIDECAR-18] Improve auth errors handling

---

pom.xml

Since we've released several libraries, it would be great to update dependency versions.
- update dependency versions
- change application version 0.0.1 -> 1.0.0
- add scm in pom.xml
- fix plugin dependency issue

Fix: update versions

---

README.md
src/main/java/org/folio/sidecar/configuration/properties/WebClientProperties.java
src/main/java/org/folio/sidecar/service/routing/RequestForwardingService.java
src/main/resources/application.properties
src/test/java/org/folio/sidecar/it/SidecarIT.java
src/test/java/org/folio/sidecar/service/routing/RequestForwardingServiceTest.java
src/test/resources/application.properties
src/test/resources/mappings/mod-bar-0.5.1.json
src/test/resources/mappings/mod-foo-0.2.1.json

https://issues.folio.org/browse/MODSIDECAR-3
- added configurable property
- updated unit tests and readme
- added IT test cases
environment. Communication is paramount if that is to be achieved, especially as the number of …

MODSIDECAR-3: Configurable request timeouts

---

src/main/java/org/folio/sidecar/model/error/ErrorCode.java
src/main/java/org/folio/sidecar/service/ErrorHandler.java
src/test/java/org/folio/sidecar/it/SidecarIT.java

https://folio-org.atlassian.net/browse/MODSIDECAR-24
Change error response and code
Return 408 code - for read timeout
environment. Communication is paramount if that is to be achieved, especially as the number of …

MODSIDECAR-24: if read timeout return 408

---

src/main/java/org/folio/sidecar/service/filter/SelfRequestFilter.java
src/main/java/org/folio/sidecar/service/routing/IngressRequestHandler.java
src/main/java/org/folio/sidecar/utils/RoutingUtils.java
src/test/java/org/folio/sidecar/service/routing/IngressRequestHandlerTest.java

Fixes an issue, when module requests were not detected as self-request (missing header) and then they are cannot be routed to the valid URL.
- Always update path with prefix if this option is enabled
environment. …

MODSIDECAR-26 Update path prefix for any ingress request

---

src/main/resources/application.properties

Add default values for TLS properties and set explicitly Quarkus HTTPS port …

MODSIDECAR-41: Add default values for TLS properties

---

README.md
pom.xml
src/main/java/org/folio/sidecar/configuration/SecureStoreConfiguration.java
src/main/java/org/folio/sidecar/service/filter/DesiredPermissionsFilter.java
src/main/resources/application.properties

Add FIPS mode to AWS SSM integration
While it's helpful for reviewers to help …

EUREKA-97: Add FIPS mode to AWS SSM integration

---

src/main/java/org/folio/sidecar/integration/kafka/TenantEntitlementConsumer.java
src/main/java/org/folio/sidecar/integration/kafka/TenantEntitlementEvent.java
src/test/java/org/folio/sidecar/integration/kafka/TenantEntitlementConsumerTest.java

Consume entitlement event with UPGRADE type from mgr-tenant-entitlements
Add `UPGRADE` value to support entitlement event with `UPGRADE` type from mgr-tenant-entitlements
Tested System user deletion on **evrk2**: …

MODUSERSKC-11: Add UPGRADE value to support entitlement event with upgrade type from mgr-tenant-entitlements

---

Jenkinsfile

Automatic Docker Image build
While it's helpful for reviewers to help identify …

Rancher-1502

---

src/main/java/org/folio/sidecar/configuration/SecureStoreConfiguration.java

While it's helpful for reviewers to help identify potential problems, ensuring …

Fix AWS SSM properties

---

pom.xml

Replace 1.5.4-SNAPSHOT to released 1.5.4 version
While it's helpful for …

MODSIDECAR-43 Fix application-poc-tools dependency version

---

src/main/java/org/folio/sidecar/service/TokenCacheFactory.java

Fix master build
- remove extra logic ruins tests

Fix token cache test

---

.dockerignore
Jenkinsfile

Enable docker build in Jenkinsfile

Enable docker build in Jenkinsfile

---

Jenkinsfile

While it's helpful for reviewers to help identify potential problems, ensuring …

EPC branch for platform-complete repo and image update process

---

src/main/resources/application.properties
src/test/resources/application.properties

Change hostname verification for TLS connections enabled by default.

Change hostname verification for TLS connections enabled by default.

---

pom.xml

Increases application-poc-tools to v1.5.8-SNAPSHOT
- Use the latest snapshot versions of `applications-poc-tools` library components
environment. Communication is paramount if that is to be achieved, especially as the number …

KEYCLOAK-24 Increase applications-poc-tools to v1.5.8-SNAPSHOT

---

src/main/java/org/folio/sidecar/service/ServiceTokenProvider.java
src/main/java/org/folio/sidecar/service/SystemUserTokenProvider.java
src/main/java/org/folio/sidecar/service/filter/RequestFilterService.java
src/main/java/org/folio/sidecar/service/routing/EgressRequestHandler.java
src/test/java/org/folio/sidecar/service/routing/EgressRequestHandlerTest.java

Revert changes to the EgressHandler that are related to the async
Add token loading if cache is empty
inter-team …

Modsidecar 63: Fix performance

---

src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilter.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakImpersonationFilter.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakJwtFilter.java
src/main/java/org/folio/sidecar/service/routing/EgressRequestHandler.java
src/test/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilterTest.java
src/test/java/org/folio/sidecar/integration/keycloak/filter/KeycloakJwtFilterTest.java

[MODSIDECAR-69](https://folio-org.atlassian.net/browse/MODSIDECAR-69)
Sidecar validates user token even if system token presented
- if system token presented - validate it first
- if system token presented - skip user token validation
- do not impersonate request if system token presented
Ideally, all the PRs involved in breaking changes …

MODSIDECAR-69 [Token expiration][Eureka ECS] The user is unable to run queries successfully in Query builder on the Central tenant.

---

src/main/java/org/folio/sidecar/configuration/properties/RoutingHandlerProperties.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilter.java
src/main/java/org/folio/sidecar/service/filter/RequestFilterService.java
src/main/java/org/folio/sidecar/service/routing/EgressRequestHandler.java
src/main/java/org/folio/sidecar/service/routing/RoutingService.java
src/main/java/org/folio/sidecar/service/token/AsyncTokenCacheFactory.java
src/main/java/org/folio/sidecar/service/token/ServiceTokenProvider.java
src/main/java/org/folio/sidecar/service/token/SystemUserTokenProvider.java
src/main/java/org/folio/sidecar/service/token/TokenCacheFactory.java
src/main/java/org/folio/sidecar/utils/JwtUtils.java
src/main/java/org/folio/sidecar/utils/RoutingUtils.java
src/main/java/org/folio/sidecar/utils/TokenUtils.java
src/main/resources/application.properties
src/test/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilterTest.java
src/test/java/org/folio/sidecar/it/CrossTenantIT.java
src/test/java/org/folio/sidecar/service/routing/RoutingServiceTest.java
src/test/resources/application.properties

Add extensive debug information for incoming request and routing context data to have better visibility of inputs and ongoing processing. Additionally output token claims during keycloak authorization to see the content of token, this should help with analyzing Unauthorized errors
US: [MODSIDECAR-69](https://folio-org.atlassian.net/browse/MODSIDECAR-69)
* for incoming requests output request details: method, path, headers
* disabling or enabling of the above feature can be controlled via dedicated app properties. additionally the output can be activated only for specific paths
* if request filtering fails for some reason, log the error and additionally log request headers plus current state of routing context data. it also can be turned on/off via app prop.
* in …

MODSIDECAR-69 [Eureka ECS] The user is unable to run queries successfully in Query builder on the Central tenant.

---

src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakAuthorizationFilter.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakImpersonationFilter.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakJwtFilter.java
src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakSystemJwtFilter.java

[MODSIDECAR-74](https://folio-org.atlassian.net/browse/MODSIDECAR-74)
Module to module call should ignore expired user token if service token is active
- parse system tokens even for endpoints without permissions requered section
Ideally, all the PRs involved in breaking changes would be merged on the same day to avoid breaking the …

MODSIDECAR-74: 401 Unauthorized error for m2m requests

---

src/main/java/org/folio/sidecar/service/ErrorHandler.java
src/main/java/org/folio/sidecar/service/TransactionLogHandler.java
src/main/java/org/folio/sidecar/service/filter/RequestFilterService.java
src/main/java/org/folio/sidecar/service/filter/SelfRequestFilter.java
src/main/java/org/folio/sidecar/service/routing/EgressRequestHandler.java
src/main/java/org/folio/sidecar/service/routing/IngressRequestHandler.java
src/main/java/org/folio/sidecar/service/routing/RequestMatchingService.java
src/main/java/org/folio/sidecar/service/routing/RoutingService.java
src/main/java/org/folio/sidecar/utils/RoutingUtils.java
src/test/java/org/folio/sidecar/it/ForwardEgressTlsIT.java
src/test/java/org/folio/sidecar/it/SidecarIT.java
src/test/java/org/folio/sidecar/service/ErrorHandlerTest.java
src/test/java/org/folio/sidecar/service/filter/SelfRequestFilterTest.java
src/test/java/org/folio/sidecar/service/routing/IngressRequestHandlerTest.java
src/test/resources/mappings/am/mod-foo-0.2.1-boostrap.json
src/test/resources/mappings/mod-bar-0.5.1.json
src/test/resources/mappings/mod-foo-0.2.1.json

Socket timeout errors appear while upload file with valid identifiers in Bulk edit on Eureka environment. The issue noticed for all record type identifiers - Instances, Holdings, Items and Users. The issue reproduced occasionally on small dataset. The issue reproduced constantly on larger dataset ~10K+ file with identifiers
Note: the PR doesn't solve the issue but rather improve request tracing to help investigate it
US: [MODSIDECAR-86](https://folio-org.atlassian.net/browse/MODSIDECAR-86)
* improve request tracing by logging complete uri (with query parameters) instead of path part only
* verify that sidecar correctly passes request query during ingress and egress handling
- Does this PR meet or …

MODSIDECAR-86 Socket timeout errors appear while upload file with valid identifiers in Bulk edit on Eureka environment

---

src/main/java/org/folio/sidecar/integration/keycloak/filter/KeycloakJwtFilter.java
src/main/java/org/folio/sidecar/service/TenantService.java
src/main/java/org/folio/sidecar/service/token/ServiceTokenProvider.java
src/main/java/org/folio/sidecar/service/token/SystemUserTokenProvider.java

To reduce unnecessary calls to the SSM for cases where the sidecar works for a module without a system user, delete the automatic cache loading for the system user’s cache upon Entitlement events.
- Remove system user cache loading in the sync cache method
Ideally, all the PRs involved in breaking changes would be merged on the same day to …

MODSIDECAR-85: options for reducing number of Secret Store

---

pom.xml
src/main/resources/reflection-config.json

Fix AWS Client for native binaries 
[EUREKASUP-41](https://folio-org.atlassian.net/browse/EUREKASUP-41)
Add Explicit HTTP Client declaration
Add Reflection Config for AWS Client
environment. Communication is paramount if …

Eurekasup 41: Build native images

---

Dockerfile
Jenkinsfile
README.md
docker/Dockerfile.fips
pom.xml

Use Java version 21
While it's helpful for reviewers to help identify …

MODSIDECAR-99

---

src/main/java/org/folio/sidecar/service/filter/RequestFilterService.java
src/main/java/org/folio/sidecar/service/routing/configuration/RoutingConfiguration.java
src/main/java/org/folio/sidecar/service/routing/handler/EgressRequestHandler.java
src/main/java/org/folio/sidecar/service/routing/handler/IngressRequestHandler.java
src/main/java/org/folio/sidecar/service/routing/handler/RequestForwardingService.java
src/main/java/org/folio/sidecar/service/routing/handler/RoutingEntryHandler.java
src/main/java/org/folio/sidecar/service/routing/handler/RoutingHandlerWithLookup.java
src/main/java/org/folio/sidecar/service/routing/handler/ScRequestHandler.java
src/test/java/org/folio/sidecar/service/routing/ScRequestHandlerTest.java
src/test/java/org/folio/sidecar/service/routing/handler/EgressRequestHandlerTest.java
src/test/java/org/folio/sidecar/service/routing/handler/IngressRequestHandlerTest.java
src/test/java/org/folio/sidecar/service/routing/handler/RequestForwardingServiceTest.java

Fail the chained handler if the underlying routing entry handler fails. Also, retrieve the execution result from the request forwarding service as a future. This future influences how the routing entry handler completes.
US: [MODSIDECAR-102](https://folio-org.atlassian.net/browse/MODSIDECAR-102)
* `RoutingEntryHandler` now returns `Future<Void>`
* if `RoutingEntryHandler` fails it will fail the whole chain
* pass a `Promise` to `RequestForwardingService` to get completion result from it
- What other modules will these changes …

MODSIDECAR-102: Fail chained handler if underlying routing entry handler fails

---

src/main/java/org/folio/sidecar/service/routing/handler/RequestForwardingService.java
src/test/java/org/folio/sidecar/it/DynamicRoutingIT.java
src/test/java/org/folio/sidecar/service/routing/handler/RequestForwardingServiceTest.java

Added HTTP chunked encoding for request and response handling.

MODSIDECAR-103: Added HTTP chunked encoding for request and response 

---

pom.xml
src/main/java/org/folio/sidecar/configuration/WebClientConfiguration.java
src/main/java/org/folio/sidecar/service/TransactionLogHandler.java
src/main/java/org/folio/sidecar/service/routing/RequestForwardingService.java
src/test/java/org/folio/sidecar/configuration/WebClientConfigurationTest.java
src/test/java/org/folio/sidecar/service/routing/RequestForwardingServiceTest.java

[MODSIDECAR-101](https://folio-org.atlassian.net/browse/MODSIDECAR-101) - Backport to Ramsons CSP: HTTP streaming support
environment. Communication is paramount if that is to be achieved, especially as the number of …

Release 2.0.8

---

src/main/java/org/folio/sidecar/service/token/ServiceTokenProvider.java
src/main/java/org/folio/sidecar/service/token/SystemUserTokenProvider.java
src/test/java/org/folio/sidecar/it/DynamicRoutingIT.java
src/test/java/org/folio/sidecar/service/routing/handler/EgressRequestHandlerTest.java
src/test/java/org/folio/sidecar/service/token/ServiceTokenProviderTest.java
src/test/java/org/folio/sidecar/service/token/SystemUserTokenProviderTest.java
src/test/java/org/folio/sidecar/support/TestConstants.java

Several tests have been disabled in sidecar due to emergent fixes or issues on Jenkins. They should be revised and fixed, if possible. If it doesn't make sense to fix a test, because it’s outdated, then is should be removed.
US: [MODSIDECAR-107](https://folio-org.atlassian.net/browse/MODSIDECAR-107)
* rewrite following unit tests: `ServiceTokenProviderTest`, `SystemUserTokenProviderTest`, `EgressRequestHandlerTest`
* re-enable integration tests: `DynamicRoutingIT`
- Do Rally …

MODSIDECAR-107 Review previously disabled tests, make them work or remove

---

.github/PULL_REQUEST_TEMPLATE.md
NEWS.md

Explain why these changes are needed and link the related issue (e.g., https://folio-org.atlassian.net/browse/PROJ-123).
Provide a brief technical summary of the changes.
---

update pull request template

---

NEWS.md
pom.xml
src/main/java/org/folio/sidecar/service/RetryTemplate.java
src/main/java/org/folio/sidecar/service/routing/handler/RequestForwardingService.java
src/test/java/org/folio/sidecar/service/RetryTemplateTest.java
src/test/java/org/folio/sidecar/service/routing/handler/RequestForwardingServiceTest.java

https://folio-org.atlassian.net/browse/MODSIDECAR-108
Using the right strategy for request creation is important based on whether the URL is presented with a port or not. 
- add condition on port
- add tests
- rewrite retry template (previous implementation contained depricated interfaces)
---

MODSIDECAR-108: fix missing port issue

---

pom.xml
src/main/java/org/folio/sidecar/health/HealthCheckPayloadConstants.java
src/main/java/org/folio/sidecar/health/HealthCheckPayloadUtils.java
src/main/java/org/folio/sidecar/health/ModuleHealthCheck.java
src/main/java/org/folio/sidecar/health/RemoveChecksFilter.java
src/main/java/org/folio/sidecar/health/RemoveDataFromNamedCheckFilter.java
src/main/java/org/folio/sidecar/health/configuration/HealthCheckConfiguration.java
src/main/resources/application.properties
src/test/java/org/folio/sidecar/health/HealthCheckPayloadUtilsTest.java
src/test/java/org/folio/sidecar/health/ModuleHealthCheckTest.java
src/test/java/org/folio/sidecar/health/RemoveChecksFilterTest.java
src/test/java/org/folio/sidecar/health/RemoveDataFromNamedCheckFilterTest.java
src/test/java/org/folio/sidecar/it/HealthCheckIT.java
src/test/java/org/folio/sidecar/it/SidecarIT.java

Backport [MODSIDECAR-109](https://folio-org.atlassian.net/browse/MODSIDECAR-109) Simplify the health check response to Ramsons
US: [MODSIDECAR-110](https://folio-org.atlassian.net/browse/MODSIDECAR-110)

MODSIDECAR-110 Backport MODSIDECAR-109 to Ramsons

---

README.md
docker/Dockerfile.native-micro
pom.xml
src/main/resources/application.properties

Explain why these changes are needed and link the related issue (e.g., https://folio-org.atlassian.net/browse/PROJ-123).
Provide a brief technical summary of the changes.
---

RANCHER-2116 Make Native SC image target CPU configurable

---

NEWS.md
README.md
src/main/java/org/folio/sidecar/integration/cred/configuration/SecureStoreConfiguration.java
src/main/resources/application.properties

Introduce configuration for Folio Secure Store Proxy (FSSP).
US: [APPPOCTOOL-59](https://folio-org.atlassian.net/browse/APPPOCTOOL-59)
* add configuration to make it possible to connect to and retrieve secrets from FSSP

APPPOCTOOL-59 Introduce configuration for FSSP

---

NEWS.md
pom.xml

See [MODSIDECAR-137](https://folio-org.atlassian.net/browse/MODSIDECAR-137) Fix native image build
- Exclude log4j-core from dependencies in pom.xml
---

MODSIDECAR-137: Native sidecar build issue

---

src/main/java/org/folio/sidecar/integration/users/UserService.java

Fixing native sidecar native image for case [MODSIDECAR-139:](https://folio-org.atlassian.net/browse/MODSIDECAR-139)
- PermissionContainer marked as @RegisterForReflection
---

MODSIDECAR-139: (Native sidecar ECS) Cannot switch affiliation

---

NEWS.md
src/main/java/org/folio/sidecar/service/TenantService.java
src/test/java/org/folio/sidecar/service/TenantServiceTest.java

Fix the problem when the Tenant is not enabled. [MODSIDECAR-141](https://folio-org.atlassian.net/browse/MODSIDECAR-141)
- refined condition for retrieving entitlement information
---

MODSIDECAR-141: Server unreachable | Application not enabled
